ARG BASE_IMAGE_NAME="sentoz/multi-sonarqube-scanner-cli"
ARG BASE_IMAGE_TAG="latest-base-jammy"
FROM $BASE_IMAGE_NAME:$BASE_IMAGE_TAG

LABEL org.opencontainers.image.authors="Dmitriy Okladin <sentoz66@gmail.com>"
LABEL org.opencontainers.image.source="https://github.com/sentoz/multi-sonarqube-scanner-cli"

ARG GRADLE_VERSION=8.1.1

ARG SONARQUBE_TOKEN
ARG SONARQUBE_URL

ARG SONAR_SCANNER_HOME=/opt/sonar-scanner
ARG GRADLE_HOME=/opt/gradle

ENV HOME=/tmp
ENV XDG_CONFIG_HOME=/tmp
ENV SONAR_SCANNER_HOME=$SONAR_SCANNER_HOME
ENV SONAR_USER_HOME=$SONAR_SCANNER_HOME/.sonar
ENV PATH=$SONAR_SCANNER_HOME/bin:$PATH
ENV NODE_PATH=/usr/lib/node_modules
ENV SRC_PATH=/usr/src
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

WORKDIR /opt

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# hadolint ignore=DL3008,DL3013,DL3016,DL3028,SC2015,SC1001
RUN set -eux; \
    wget -U "scannercli" -q -O /opt/gradle.zip "https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"; \
    unzip /opt/gradle.zip; \
    rm /opt/gradle.zip; \
    mv "/opt/gradle-$GRADLE_VERSION" "$GRADLE_HOME/"; \
    ln -s "$GRADLE_HOME/bin/gradle" /usr/bin/gradle;

WORKDIR $SRC_PATH

ENTRYPOINT ["/usr/bin/docker_entrypoint"]